---
title: '<span style="font-size:48pt;">Example and Deployment</span>'
subtitle: 'X Y Z'
author: 'Pittsburgh Summer Methodology Series'
date: 'Day 3D &emsp; &emsp; August 10, 2022'
output:
  xaringan::moon_reader:
    css: [../css/xaringan-themer.css, ../css/styles.css]
    nature:
      slideNumberFormat: "%current% / %total%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
      navigation:
        scroll: false
    self_contained: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  fig.showtext = TRUE,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE,
  collapse = TRUE
)
```

```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_tachyons()
xaringanExtra::use_clipboard()
xaringanExtra::use_tile_view()
```

```{r packages, echo=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(countdown)
library(patchwork)
library(xaringanthemer)
library(tidymodels)
tidymodels_prefer()
```

class: inverse, center, middle
# Section 1

---

## Live Coding: Read in data

```{r, eval=FALSE}
library(tidyverse)
library(tidymodels)
tidymodels_prefer()

water <- read_csv("https://tinyurl.com/water-pm")
head(water)
```

```{r, echo=FALSE}
water <- read_csv("../data/water.csv")
water %>% 
  head() %>% 
  kable(digits = 2) %>% 
  kable_styling(font_size = 17)
```


<!-- pot_split <- initial_split(water, prop = 0.8, strata = Potability) -->

<!-- pot_train <- training(pot_split) -->
<!-- pot_test <- testing(pot_split) -->

<!-- pot_folds <- vfold_cv(pot_train, v = 10, repeats = 1, strata = Potability) -->
<!-- pot_folds -->

<!-- pot_recipe <-  -->
<!--   recipe(pot_train, Potability ~ .) %>%  -->
<!--   step_mutate(Potability = factor(Potability)) %>%  -->
<!--   step_dummy(all_nominal_predictors()) %>% -->
<!--   step_nzv(all_predictors()) %>% -->
<!--   step_corr(all_numeric_predictors()) %>% -->
<!--   step_lincomb(all_numeric_predictors()) %>%  -->
<!--   step_normalize(all_predictors()) -->

<!-- rf_model <-  -->
<!--   rand_forest(mtry = tune(), trees = tune(), min_n = tune()) %>%  -->
<!--   set_mode("classification") %>%  -->
<!--   set_engine("ranger", importance = "impurity") -->


<!-- pot_wflow <-  -->
<!--   workflow() %>%  -->
<!--   add_recipe(pot_recipe) %>%  -->
<!--   add_model(rf_model) -->

<!-- pot_param <-  -->
<!--   rf_model %>%  -->
<!--   extract_parameter_set_dials() %>%  -->
<!--   finalize(pot_folds) -->

<!-- pot_tune <-  -->
<!--   pot_wflow %>%  -->
<!--   tune_grid( -->
<!--     resamples = pot_folds, -->
<!--     grid = 10, -->
<!--     param_info = pot_param -->
<!--   ) -->

<!-- autoplot(pot_tune) -->

<!-- # Select the best parameters values -->

<!-- pot_param_final <- select_best(pot_tune, metric = "roc_auc") -->
<!-- pot_param_final -->

<!-- # Finalize the workflow with best parameter values -->

<!-- pot_wflow_final <-  -->
<!--   pot_wflow %>%  -->
<!--   finalize_workflow(pot_param_final) -->
<!-- pot_wflow_final -->

<!-- pot_fitr <-  -->
<!--   pot_wflow_final %>%  -->
<!--   fit_resamples( -->
<!--     resamples = pot_folds -->
<!--   ) -->

<!-- collect_metrics(pot_fitr) -->


<!-- pot_final <-  -->
<!--   pot_wflow_final %>%  -->
<!--   last_fit(pot_split) -->

<!-- collect_metrics(pot_final) -->

<!-- library(vip) -->
<!-- pot_final %>%  -->
<!--   extract_fit_parsnip() %>%  -->
<!--   vip() -->



---

class: inverse, center, middle
# Section 2

---
class: inverse, center, middle
# Time for a Break!
```{r countdown, echo=FALSE}
countdown(
  minutes = 10, 
  seconds = 0, 
  right = "33%", 
  left = "33%",
  bottom = "15%",
  color_background = "white",
  color_text = "black",
  color_running_background = "white",
  color_running_text = "black",
  warn_when = 60
)
```
