---
title: "About the Course"
output: 
  html_document:
    toc: FALSE
---

This is a synchronous, online course taking place as part of the [Pittsburgh Summer Methodology Series](https://www.pittmethods.com) on August 8-11, 2022. Each of these four days will run for between 10:30am - 3:30pm (New York Time/EDT/UTC-4:00) with an hour lunch break from 12:30pm - 1:30pm (approximately). Enrollment in the course and access to the video recordings requires registration, which can be purchased through the [Pitt Methods website](https://www.pittmethods.com/applied-ml); we are pleased to offer a discounted rate for students and trainees. However, materials (slides and activities) are freely available through this website and may be re-used according to the [CC-BY License](https://github.com/PittMethods/appliedml/blob/main/LICENSE.txt).

---

## Course Schedule

| Day | Part | Topic                             | Lead   | Video Link                     |
| :-: | :--: | :-------------------------------- | :----- | :----------------------------- |
| 1   | A    | Conceptual introductions          | Girard | <https://youtu.be/7ex-Ylu4grs> |
|     | B    | Tidyverse primer and data         | Girard | <https://youtu.be/7ex-Ylu4grs> |
|     | C    | Data splitting and validation     | Wang   | <https://youtu.be/CbfxZRWlTkI> |
|     | D    | Model fitting and prediction      | Wang   | <https://youtu.be/CbfxZRWlTkI> |
| 2   | A    | Workflows and recipes             | Girard | <https://youtu.be/0xkuhznD60U> |
|     | B    | Performance evaluation            | Girard | <https://youtu.be/0xkuhznD60U> |
|     | C    | Resampling and cross-validation   | Wang   | <https://youtu.be/0Nkli0B0jC8> |
|     | D    | Building a model: start to finish | Wang   | <https://youtu.be/0Nkli0B0jC8> |
| 3   | A    | Regularization and elastic net    | Wang   | <https://youtu.be/g51MRN9E6yk> |
|     | B    | GLMNET example and tuning         | Girard | <https://youtu.be/g51MRN9E6yk> |
|     | C    | Decision trees and random forests | Wang   | <https://youtu.be/XCqL9UAuDF8> |
|     | D    | RF example and reporting          | Girard | <https://youtu.be/XCqL9UAuDF8> |
| 4   | A    | Support vector machines           | Girard | TBA                            |
|     | B    | Practical issues                  | Wang   | TBA                            |
|     | C    | Consulting                        |        | NA                             |
|     | D    | Consulting                        |        | NA                             |


Video recordings of the course meetings are posted as private YouTube videos (see the links in the table above). It may take up to 6 hours for the high definition versions of the videos to be ready on YouTube. In order to access the videos, you must log into YouTube using the email address that was invited to view it. If you would like us to invite a different email address than the one you registered for the course with, please let us know via email or Slack direct message.

---

## Course Communication

Important announcements will be emailed to registered attendees. However, attendees are strongly encouraged to join the course's Slack workspace. This workspace will provide a place for questions, answers, comments, and other discussions to occur in a more permanent place. We will monitor the Zoom chat window but this disappears when you leave a meeting, so Slack is the preferred method for communication. There will be several channels for discussion of different topics (i.e., `#announcements` for news and updates related to the course, `#general` for questions and comments related to the course, and `#random` for questions and comments unrelated to the course). More personal or sensitive communications should occur via email or Slack direct messages.

- An invitation to join this Slack workspace was emailed to registered attendees.

- If you are new to Slack, [click here for an introductory guide](https://slack.com/help/articles/218080037-Getting-started-for-new-Slack-users)

---

## Course Conduct

**Etiquette:**

- Behave professionally at all times
- Stay on topic and minimize distractions
- Stay muted unless talking (to minimize noise)
- Ask questions in Slack or use "Raise Hand"
- Be respectful to everyone in the workshop
- Be patient with yourself and others

**You have the right to:**

- Be treated with respect at all times
- Turn your camera on or off
- Arrive and depart whenever needed
- Ask for help with workshop content
- Share your opinions respectfully
- Reuse materials according to the license
- Receive reasonable accommodations
- Contact the instructors by email
