---
title: "Course Datasets"
output: 
  html_document:
    toc: FALSE
    df_print: paged
    self-contained: true
---

The following datasets will be used in the course:

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
```

## airsat

Real data on the satisfaction and experience of 10,000 customers of an airline <a href="https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction" class="badge badge-info">Info</a>

```{r, eval=FALSE}
# install.packages("readr")
airsat <- readr::read_csv("https://tinyurl.com/amlr-airsat") |> print()
```

```{r, echo=FALSE, message=FALSE}
# https://github.com/PittMethods/appliedml/blob/main/data/airsat.csv
read_csv("./data/airsat.csv", show_col_types = FALSE)
```

---

## spotify

Real data on the popularity and acoustic properties of 5,000 songs from Spotify <a href="https://www.kaggle.com/datasets/yasserh/song-popularity-dataset" class="badge badge-info">Info</a>

```{r, eval=FALSE}
# install.packages("readr")
spotify <- readr::read_csv("https://tinyurl.com/amlr-spotify") |> print()
```

```{r, echo=FALSE, message=FALSE}
# https://github.com/PittMethods/appliedml/blob/main/data/spotify.csv
read_csv("./data/spotify.csv", show_col_types = FALSE)
```

---

## titanic

Real data on 1,309 passengers on the Titanic <a href="https://www.openml.org/search?type=data&sort=runs&id=40945&status=active" class="badge badge-info">Info</a>


```{r, eval=FALSE}
# install.packages("readr")
titanic <- readr::read_csv("https://tinyurl.com/amlr-titanic") |> print()
```

```{r, echo=FALSE, message=FALSE}
# https://github.com/PittMethods/appliedml/blob/main/data/titanic.csv
read_csv("./data/titanic.csv", show_col_types = FALSE)
```

---

## water

Real data on the potability and chemical properties of 3,276 water bodies <a href="https://www.kaggle.com/adityakadiwal/water-potability" class="badge badge-info">Info</a>

```{r, eval=FALSE}
# install.packages("readr")
water <- readr::read_csv("https://tinyurl.com/amlr-water") |> print()
```

```{r, echo=FALSE, message=FALSE}
# https://github.com/PittMethods/appliedml/blob/main/data/water.csv
read_csv("./data/water.csv", show_col_types = FALSE)
```
