---
title: "Day 1D Live Coding<br />(Fitting Models)"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    df_print: paged
editor_options: 
  chunk_output_type: inline
---


```{r, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  df_print = "paged"
)
```

# Load packages

```{r, message=FALSE}
library(tidyverse)
library(tidymodels)
```

---

# Data Preparation

```{r}
affect <- read.csv("../data/affect.csv")

# select variables 
affect <- affect %>% 
  select(ext, neur, imp, soc, BDI) %>% 
  drop_na()

# view
head(affect)
```


---

# Goal:

We will aim to predict `BDI` (depression) scores from personality variables, including: 

- Extraversion

- Neuroticism

- Impulsivity

- Sociability 

---

# Split Data 

```{r}
affect_split <- initial_split(affect, prop = 0.8, strata = 'BDI')
affect_train <- training(affect_split)
affect_test <- testing(affect_split)

dim(affect_train)
dim(affect_test)
```

---

# Specify and Fit Model

```{r}
# specify model
ols_reg <- linear_reg() %>% 
  set_engine("lm")

# fit model
bdi_fit <- ols_reg %>% 
  fit(BDI ~ ., data = affect_train)
```

---

# Inspect Results

```{r}
# coefficients 
tidy(bdi_fit)

# training performance
glance(bdi_fit)
```

---

# Training Set Performance

```{r}
glance(bdi_fit)
```

---

# Make Predictions on Test Set

```{r}
bdi_test_preds <- predict(bdi_fit, new_data = affect_test)
bdi_test_preds

# merge predictions with test data 

bdi_preds <- affect_test %>% 
  select(BDI) %>%
  bind_cols(bdi_test_preds)
```

---

# Visualize Predicted vs Trusted Data

```{r, warning=FALSE}
qplot(x = bdi_preds$BDI, y = bdi_preds$.pred) + geom_abline()
```

---

# Estimating Test Set Performance 

```{r}
# create a performance metrics set 
affect_metrics <- metric_set(rmse, rsq, mae)

affect_metrics(bdi_preds, truth = BDI, estimate = .pred)
```





