---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(patchwork)
set.seed(2021)
```

```{r}
signal <- function(x) {sin(2*pi*x)}
x_linspace <- seq(0, 1, by = 0.02)
x_data <- runif(length(x_linspace), 0, 1)
y_true <- signal(x_linspace)
y_data <- signal(x_data) + rnorm(length(x_data), 0, 0.25)
dat <- tibble(
  x_linspace,
  x_data,
  y_true,
  y_data
)
```

```{r}
p0 <- 
  ggplot(dat) + 
  geom_point(aes(x = x_data, y = y_data), shape = 1, size = 3, color = "grey30") + 
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "", x = "feature", y = "label") +
  theme_classic(base_size = 20)

p1 <- 
  ggplot(dat) + 
  geom_point(aes(x = x_data, y = y_data), shape = 1, size = 3, color = "grey30") + 
  stat_smooth(
    aes(x = x_data, y = y_data), 
    method = "lm", 
    se = FALSE,
    formula = y ~ x, 
    color = "blue",
    size = 1.5
  ) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Underfit", x = "feature", y = "label") +
  theme_classic(base_size = 20)

p2 <- 
  ggplot(dat) + 
  geom_point(aes(x = x_data, y = y_data), shape = 1, size = 3, color = "grey30") + 
  stat_smooth(
    aes(x = x_data, y = y_data), 
    method = "lm",
    se = FALSE,
    formula = y ~ poly(x, 17), 
    color = "red",
    size = 1.5
  ) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Overfit", x = "feature", y = NULL) +
  theme_classic(base_size = 20)

p3 <- 
  ggplot(dat) + 
  geom_point(aes(x = x_data, y = y_data), shape = 1, size = 3, color = "grey30") + 
  stat_smooth(
    aes(x = x_data, y = y_data), 
    method = "lm",
    se = FALSE,
    formula = y ~ poly(x, 4), 
    color = "purple",
    size = 1.5
  ) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(title = "Good Fit", x = "feature", y = NULL) +
  theme_classic(base_size = 20)
```

```{r}
p0 | (p0 + labs(y = NULL)) | (p0 + labs(y = NULL))
ggsave("three_empty.png", width = 12.33, height = 5, units = "in")

p1 | p3 | p2
ggsave("three.png", width = 12.33, height = 5, units = "in")
```

```{r}
p0 + labs(title = NULL)
ggsave("p0.png", width = 5.5, height = 4, units = "in")

p3 + labs(title = NULL, y = "label")
ggsave("p3.png", width = 5.5, height = 4, units = "in")

```


